name: DiscordLink
version: '${project.version}'
main: com.devnics.DiscordLink.DiscordLinkPlugin
api-version: 1.19
depend:
  - Vault
  - PlaceholderAPI
commands:
  link:
    description: Links your account
    usage: /link